### PR TITLE
Use explicit import lists, fixes build with time 1.9

### PR DESCRIPTION
**Pull request by fgaz**
It should also make it more robust to future changes

### CODE REVIEW

**Comment by fgaz** [comment]
Friendly ping :)

**Comment by portnov** [comment]
Hello
Will try to test and merge this week.

**Comment by fgaz** [comment]
Nice! Could you also make an hackage release if you have the time?

**Comment by portnov** [comment]
done.
http://hackage.haskell.org/package/dates-0.2.3.0

**Comment by fgaz** [comment]
Awesome, thanks!
[It's all green now :)](https://matrix.hackage.haskell.org/#/package/dates)

**Pull request merged**
